language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - nightly

matrix:
  allow_failures:
    - php: nightly

install:
  - composer install --dev

script:
  - mkdir -p build/logs
  - phpunit --coverage-clover build/logs/clover.xml Tests

#after_script:
#  - vendor/bin/coveralls -v
